[project]
name = "yvideo-py"
version = "0.1.0"
description = "Copyright-safe course-based media sharing"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.3",
]

[dependency-groups]
dev = [
    "pre-commit>=3.0.0",
    "ruff>=0.1.0",
]
