# Generated by Django 5.2.15 on 2026-08-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='clips_only',
            field=models.BooleanField(default=False, verbose_name='Show only clips defined in the editor (better Fair Use protection)'),
        ),
    ]
