# Generated by Django 5.2.15 on 2026-08-05 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_content_clips_only"),
    ]

    operations = [
        migrations.RenameField(
            model_name="language",
            old_name="lang_tag",
            new_name="iso_639_3",
        ),
        migrations.AlterField(
            model_name="language",
            name="iso_639_3",
            field=models.CharField(
                help_text="Three-letter ISO 639-3 code. See https://iso639-3.sil.org/code_tables/639/data",
                max_length=3,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_iso_639_3",
                        message="Must be a three-letter lowercase ISO 639-3 code (e.g., eng, spa).",
                        regex="^[a-z]{3}$",
                    )
                ],
            ),
        ),
    ]
