# Generated by Django 5.2.17 on 2026-08-11 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_resource_identifier_uniqueness'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearterm', models.CharField(max_length=5, unique=True)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='annotationset',
            unique_together={('name', 'resource', 'owner')},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='public',
        ),
        migrations.AddField(
            model_name='annotationset',
            name='previous_owner',
            field=models.CharField(blank=True, help_text='Display name and netid of the owner at the time the set was orphaned. Preserves attribution after the owner deletes the set or their account.', max_length=255),
        ),
        migrations.AlterField(
            model_name='annotationset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_annotation_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='annotationset',
            name='editors',
        ),
    ]
