# Generated by Django 5.2.17 on 2026-08-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_playlistless_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legacymigrationrequest',
            name='target_collection_public',
        ),
    ]
