# Generated by Django 5.2.17 on 2026-08-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_legacymigrationrequest_target_collection_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blurannotationposition',
            name='blur_amount',
        ),
    ]
