# Generated by Django 5.2.17 on 2026-08-13 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_blurannotationposition_blur_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='words',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='words',
        ),
        migrations.DeleteModel(
            name='ImportantWord',
        ),
    ]
