# Generated by Django 5.2.17 on 2026-09-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_drop_auditor_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='allow_notes',
        ),
    ]
