# Generated by Django 5.2.17 on 2026-09-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_content_allow_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skipannotation',
            name='message',
        ),
    ]
