# Generated by Django 5.2.17 on 2026-09-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_content_allow_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name_disambiguator',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('name', 'name_disambiguator')},
        ),
    ]
