# Generated by Django 5.2.17 on 2026-09-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_content_allow_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationset',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
