# Generated by Django 5.2.17 on 2026-09-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_resource_name_disambiguator_alter_resource_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name_disambiguator',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('name', 'name_disambiguator'), name='unique_resource_name_and_disambiguator'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(condition=models.Q(('name_disambiguator__isnull', True)), fields=('name',), name='unique_undisambiguated_resource_name'),
        ),
    ]
