# Generated by Django 5.2.17 on 2026-09-23 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_skipannotation_message'),
        ('core', '0014_alter_resource_unique_together_and_more'),
    ]

    operations = [
    ]
