# Generated by Django 5.2.17 on 2026-09-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20260923_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceintakerequest',
            name='resource_name_disambiguator',
            field=models.CharField(blank=True, default='', help_text='Provide some information that would differentiate this resource from another of the same name (e.g. release year, starting actor/actress, or director)'),
        ),
    ]
