# Generated by Django 5.2.17 on 2026-09-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_resourceintakerequest_resource_name_disambiguator'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resourceintakerequest',
            constraint=models.UniqueConstraint(fields=('resource_title', 'resource_name_disambiguator'), name='unique_resource_title_and_disambiguator'),
        ),
    ]
