"""Default languages seeded into the Language table after every migration.

Covers every language in the ISO 639-1 set (that standard's own scope is
"major languages of the world"), plus a handful of languages taught at BYU
(https://cls.byu.edu/language-classes) that have no ISO 639-1 code. Every
entry is tagged with its ISO 639-3 code
(https://iso639-3.sil.org/code_tables/639/data), since Language.iso_639_3
requires that scheme.

Each entry is a (name, iso_639_3) pair. See DEFAULT_LANGUAGES.seed_languages().
"""

# Languages with an ISO 639-1 code, identified here by their ISO 639-3 code.
MAJOR_LANGUAGES = [
    ("Afar", "aar"),
    ("Abkhazian", "abk"),
    ("Avestan", "ave"),
    ("Afrikaans", "afr"),
    ("Akan", "aka"),
    ("Amharic", "amh"),
    ("Aragonese", "arg"),
    ("Arabic", "ara"),
    ("Assamese", "asm"),
    ("Avaric", "ava"),
    ("Aymara", "aym"),
    ("Azerbaijani", "aze"),
    ("Bashkir", "bak"),
    ("Belarusian", "bel"),
    ("Bulgarian", "bul"),
    ("Bislama", "bis"),
    ("Bambara", "bam"),
    ("Bengali", "ben"),
    ("Tibetan", "bod"),
    ("Breton", "bre"),
    ("Bosnian", "bos"),
    ("Catalan", "cat"),
    ("Chechen", "che"),
    ("Chamorro", "cha"),
    ("Corsican", "cos"),
    ("Cree", "cre"),
    ("Czech", "ces"),
    ("Church Slavic", "chu"),
    ("Chuvash", "chv"),
    ("Welsh", "cym"),
    ("Danish", "dan"),
    ("German", "deu"),
    ("Divehi", "div"),
    ("Dzongkha", "dzo"),
    ("Ewe", "ewe"),
    ("Greek", "ell"),
    ("English", "eng"),
    ("Esperanto", "epo"),
    ("Spanish", "spa"),
    ("Estonian", "est"),
    ("Basque", "eus"),
    ("Persian", "fas"),
    ("Fulah", "ful"),
    ("Finnish", "fin"),
    ("Fijian", "fij"),
    ("Faroese", "fao"),
    ("French", "fra"),
    ("Western Frisian", "fry"),
    ("Irish", "gle"),
    ("Scottish Gaelic", "gla"),
    ("Galician", "glg"),
    ("Guarani", "grn"),
    ("Gujarati", "guj"),
    ("Manx", "glv"),
    ("Hausa", "hau"),
    ("Hebrew", "heb"),
    ("Hindi", "hin"),
    ("Hiri Motu", "hmo"),
    ("Croatian", "hrv"),
    ("Haitian Creole", "hat"),
    ("Hungarian", "hun"),
    ("Armenian", "hye"),
    ("Herero", "her"),
    ("Interlingua", "ina"),
    ("Indonesian", "ind"),
    ("Interlingue", "ile"),
    ("Igbo", "ibo"),
    ("Sichuan Yi", "iii"),
    ("Inupiaq", "ipk"),
    ("Ido", "ido"),
    ("Icelandic", "isl"),
    ("Italian", "ita"),
    ("Inuktitut", "iku"),
    ("Japanese", "jpn"),
    ("Javanese", "jav"),
    ("Georgian", "kat"),
    ("Kongo", "kon"),
    ("Kikuyu", "kik"),
    ("Kuanyama", "kua"),
    ("Kazakh", "kaz"),
    ("Kalaallisut", "kal"),
    ("Khmer", "khm"),
    ("Kannada", "kan"),
    ("Korean", "kor"),
    ("Kanuri", "kau"),
    ("Kashmiri", "kas"),
    ("Kurdish", "kur"),
    ("Komi", "kom"),
    ("Cornish", "cor"),
    ("Kyrgyz", "kir"),
    ("Latin", "lat"),
    ("Luxembourgish", "ltz"),
    ("Ganda", "lug"),
    ("Limburgish", "lim"),
    ("Lingala", "lin"),
    ("Lao", "lao"),
    ("Lithuanian", "lit"),
    ("Luba-Katanga", "lub"),
    ("Latvian", "lav"),
    ("Malagasy", "mlg"),
    ("Marshallese", "mah"),
    ("Maori", "mri"),
    ("Macedonian", "mkd"),
    ("Malayalam", "mal"),
    ("Mongolian", "mon"),
    ("Marathi", "mar"),
    ("Malay", "msa"),
    ("Maltese", "mlt"),
    ("Burmese", "mya"),
    ("Nauru", "nau"),
    ("Norwegian Bokmål", "nob"),
    ("North Ndebele", "nde"),
    ("Nepali", "nep"),
    ("Ndonga", "ndo"),
    ("Dutch", "nld"),
    ("Norwegian Nynorsk", "nno"),
    ("Norwegian", "nor"),
    ("South Ndebele", "nbl"),
    ("Navajo", "nav"),
    ("Chichewa", "nya"),
    ("Occitan", "oci"),
    ("Ojibwa", "oji"),
    ("Oromo", "orm"),
    ("Odia", "ori"),
    ("Ossetian", "oss"),
    ("Punjabi", "pan"),
    ("Pali", "pli"),
    ("Polish", "pol"),
    ("Pashto", "pus"),
    ("Portuguese", "por"),
    ("Quechua", "que"),
    ("Romansh", "roh"),
    ("Rundi", "run"),
    ("Romanian", "ron"),
    ("Russian", "rus"),
    ("Kinyarwanda", "kin"),
    ("Sanskrit", "san"),
    ("Sardinian", "srd"),
    ("Sindhi", "snd"),
    ("Northern Sami", "sme"),
    ("Sango", "sag"),
    ("Sinhala", "sin"),
    ("Slovak", "slk"),
    ("Slovenian", "slv"),
    ("Samoan", "smo"),
    ("Shona", "sna"),
    ("Somali", "som"),
    ("Albanian", "sqi"),
    ("Serbian", "srp"),
    ("Swati", "ssw"),
    ("Southern Sotho", "sot"),
    ("Sundanese", "sun"),
    ("Swedish", "swe"),
    ("Swahili", "swa"),
    ("Tamil", "tam"),
    ("Telugu", "tel"),
    ("Tajik", "tgk"),
    ("Thai", "tha"),
    ("Tigrinya", "tir"),
    ("Turkmen", "tuk"),
    ("Tagalog", "tgl"),
    ("Tswana", "tsn"),
    ("Tongan", "ton"),
    ("Turkish", "tur"),
    ("Tsonga", "tso"),
    ("Tatar", "tat"),
    ("Twi", "twi"),
    ("Tahitian", "tah"),
    ("Uyghur", "uig"),
    ("Ukrainian", "ukr"),
    ("Urdu", "urd"),
    ("Uzbek", "uzb"),
    ("Venda", "ven"),
    ("Vietnamese", "vie"),
    ("Volapük", "vol"),
    ("Walloon", "wln"),
    ("Wolof", "wol"),
    ("Xhosa", "xho"),
    ("Yiddish", "yid"),
    ("Yoruba", "yor"),
    ("Zhuang", "zha"),
    ("Chinese", "zho"),
    ("Zulu", "zul"),
]

# Languages taught at BYU (https://cls.byu.edu/language-classes) that have no
# ISO 639-1 code.
BYU_EXTRA_LANGUAGES = [
    ("American Sign Language", "ase"),
    ("Cebuano", "ceb"),
    ("Hawaiian", "haw"),
    ("Hiligaynon", "hil"),
    ("Hmong", "hmn"),
    ("Kekchi", "kek"),
    ("K'iche'", "quc"),
    ("Gilbertese", "gil"),
    ("S'gaw Karen", "ksw"),
]

# Languages that appear in the legacy database dump
# (var/legacy_migration/legacy_dump.sqlite3) but aren't covered above, so
# legacy subtitles can still resolve to a Language row after migration.
LEGACY_DATA_LANGUAGES = [
    ("Cakchiquel", "cak"),
]

DEFAULT_LANGUAGES = MAJOR_LANGUAGES + BYU_EXTRA_LANGUAGES + LEGACY_DATA_LANGUAGES


def seed_languages(Language):
    """Ensure every language in DEFAULT_LANGUAGES exists in the given Language model.

    Existing rows are left untouched, matched by iso_639_3 so that a locally
    renamed language isn't overwritten.
    """
    existing_codes = set(Language.objects.values_list("iso_639_3", flat=True))
    Language.objects.bulk_create(
        Language(language=name, iso_639_3=code)
        for name, code in DEFAULT_LANGUAGES
        if code not in existing_codes
    )
