from datetime import timedelta
import json
import logging
import os
import re

from django.conf import settings
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.db import models
from django.db import transaction
from django.utils import timezone
import xxhash

from .utils import seconds2hms

HMS_VALIDATOR = RegexValidator(
    regex=r"^\d{1,2}:[0-5]\d:[0-5]\d(?:\.\d{1,4})?$",
    message="Time must be in H:MM:SS format (e.g., 1:23:45.67 or 12:34:56.78)",
    code="invalid_time_format",
)

logger = logging.getLogger(__name__)


class PrivilegeLevel(models.IntegerChoices):
    INSTRUCTOR = 0
    STUDENT = 1


class PlaylistRole(models.IntegerChoices):
    INSTRUCTOR = 0
    TA = 1
    STUDENT = 2
    AUDITOR = 3


LAB_ASSISTANT_GROUP_NAME = "lab_assistant"


def validate_imdb_id(id):
    """
    Accept an IMDb title ID or a generated internal Resource ID.

    IMDb title IDs begin with ``tt`` followed by at least seven digits. Resources
    that aren't listed in IMDb receive a ``BYU`` prefix followed by ten digits.
    """
    if re.fullmatch(r"(?:tt\d{7,}|BYU\d{10})", id or ""):
        return
    raise ValidationError(
        "Enter an IMDb title ID beginning with 'tt', or a generated BYU Resource ID."
    )


class Resource(models.Model):
    class MediaType(models.TextChoices):
        TEXT = ("txt", "Text")
        VIDEO = ("vid", "Video")
        WEB = ("www", "Web")
        AUDIO = ("aud", "Audio")

    name = models.CharField(max_length=255, unique=True)
    media_type = models.CharField(max_length=3, choices=MediaType.choices, blank=True)
    requester_username = models.CharField(max_length=9)
    copyrighted = models.BooleanField(default=True)
    physical_copy_exists = models.BooleanField(default=False)
    views = models.IntegerField(default=0)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    imdb_id = models.CharField(validators=[validate_imdb_id])

    # Content advisory fields
    violence_or_blood_and_gore = models.BooleanField(default=False)
    nudity_or_sexual_content = models.BooleanField(default=False)
    profanity_or_vulgarity = models.BooleanField(default=False)
    self_harm_or_suicide = models.BooleanField(default=False)
    drug_use = models.BooleanField(default=False)

    # Library ownership
    checked_out_from_hbll = models.BooleanField(
        default=False, verbose_name="Checked out from HBLL"
    )
    checked_out_from_other_byu_library = models.BooleanField(
        default=False, verbose_name="Checked out from other BYU Library"
    )

    def __str__(self):
        return f"{self.name}"

    def generate_internal_imdb_id(self):
        if not self.pk:
            raise ValueError(
                "A Resource must be saved before generating its internal ID."
            )
        self.imdb_id = "BYU" + str(self.pk).zfill(10)
        self.save(update_fields=["imdb_id"])


class CustomUserManager(BaseUserManager):
    def create_user(
        self,
        username,
        netid=None,
        privilege_level=PrivilegeLevel.STUDENT,
        password=None,
        privilege_level_override=None,
        **extra_fields,
    ):
        user = self.model(
            username=username,
            privilege_level=privilege_level,
            privilege_level_override=privilege_level_override,
            **extra_fields,
        )
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        return self.create_user(username=username, password=password, **extra_fields)


class User(AbstractUser):
    # username will be byu_id
    netid = models.CharField(max_length=8, blank=True, null=True)
    REQUIRED_FIELDS = []
    privilege_level = models.IntegerField(
        choices=PrivilegeLevel.choices, default=PrivilegeLevel.STUDENT
    )
    privilege_level_override = models.IntegerField(
        choices=PrivilegeLevel.choices, blank=True, null=True
    )
    resources = models.ManyToManyField(
        Resource, through="ResourceAccess", related_name="users"
    )
    accessible_playlists = models.ManyToManyField(
        "Playlist", through="PlaylistUserAccess", related_name="users"
    )
    courses = models.ManyToManyField("Course", through="UserCourses", blank=True)

    objects = CustomUserManager()

    def __str__(self):
        return f"{self.first_name} {self.last_name} | {self.netid} {self.username}"

    def to_dict(self):
        return {
            "netid": self.netid,
            "byuid": self.username,
            "first_name": self.first_name,
            "last_name": self.last_name,
        }

    @property
    def is_admin(self):
        return self.is_superuser

    @property
    def is_lab_assistant(self):
        return self.groups.filter(name=LAB_ASSISTANT_GROUP_NAME).count() >= 1

    def can_view_content(self, content):
        # owners and admins should have view permission even if the playlist is not published
        if content.playlist and content.playlist.owner == self:
            return True
        if self.is_admin or self.is_superuser or self.is_staff:
            return True
        if content.playlist is None:
            resource = content.get_resource()
            return bool(
                resource
                and ResourceAccess.objects.filter(user=self, resource=resource).exists()
            )
        if content.playlist.published:
            if PlaylistUserAccess.objects.filter(
                user=self, playlist=content.playlist
            ).exists():
                return True
            # TODO Check course enrollment
        return False

    def get_content_source_url(self, content):
        """URL for URL-only content, gated by the same permission check that
        protects file-backed content."""
        if content.is_url_only() and self.can_view_content(content):
            return content.url
        return None

    def get_resource_filekey(self, content):
        """Get or create a FileKey for the given content."""
        if self.can_view_content(content) and content.resource_file:
            resource_file_key = ResourceFileKey.objects.filter(
                resource_file=content.resource_file, user=self
            ).first()
            if not resource_file_key:
                resource_file_key = ResourceFileKey.objects.create(
                    resource_file=content.resource_file, user=self
                )
                resource_file_key.save()
            return resource_file_key
        else:
            return None


class ResourceAccess(models.Model):  # "through" model
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    resource = models.ForeignKey(Resource, on_delete=models.CASCADE)
    last_verified = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("user", "resource")

    def __str__(self):
        return (
            f"{self.user.netid} {self.user.username} | {self.resource.name} | {self.id}"
        )


class Playlist(models.Model):
    name = models.CharField(max_length=255)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="playlists_owned"
    )
    published = models.BooleanField(default=False)
    archived = models.BooleanField(default=False)
    public = models.BooleanField(default=False)
    courses = models.ManyToManyField("Course", related_name="playlists", blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} | {self.owner} | {self.id}"

    class Meta:
        unique_together = ("name", "owner")

    def get_instructors_and_tas(self):
        """Get all users with instructor or TA access to this playlist."""
        instructor_tas = PlaylistUserAccess.objects.filter(
            playlist=self,
            playlist_role__in=[PlaylistRole.INSTRUCTOR, PlaylistRole.TA],
        ).select_related("user")
        return [access.user for access in instructor_tas]


class PlaylistUserAccess(models.Model):  # "through" model
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    playlist_role = models.IntegerField(
        choices=PlaylistRole.choices, default=PlaylistRole.STUDENT
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("user", "playlist")

    def __str__(self):
        return f"{self.user.netid} {self.user.username} | {self.playlist.name}"


def validate_media_file(file):
    """Validate that uploaded file is video, audio, or image."""
    valid_extensions = {
        # Video
        ".mp4",
        ".avi",
        ".mov",
        ".wmv",
        ".flv",
        ".webm",
        ".mkv",
        ".m4v",
        # Audio
        ".mp3",
        ".wav",
        ".flac",
        ".aac",
        ".ogg",
        ".wma",
        ".m4a",
        # Image
        ".jpg",
        ".jpeg",
        ".png",
        ".gif",
        ".bmp",
        ".tiff",
        ".webp",
        ".svg",
    }

    ext = os.path.splitext(file.name)[1].lower()
    if ext not in valid_extensions:
        raise ValidationError(
            f"File type not supported. Must be video, audio, or image file. Got: {ext}"
        )


def _calculate_checksum_for_file(file):
    """Calculate and return the xxhash64 checksum of a file-like object."""
    if not file:
        return None
    file.seek(0)
    file_hash = xxhash.xxh64()
    for chunk in iter(lambda: file.read(4096), b""):
        file_hash.update(chunk)
    file.seek(0)  # Reset the file pointer for subsequent reads
    return file_hash.hexdigest()


def validate_unique_checksum(file):
    """Validator to ensure the uploaded file's content is unique."""
    new_checksum = _calculate_checksum_for_file(file)
    if new_checksum:
        query = ResourceFile.objects.filter(checksum=new_checksum)
        if file.instance.pk:
            query = query.exclude(pk=file.instance.pk)

        existing_file = query.first()
        if existing_file:
            raise ValidationError(
                f"A file with the same content already exists: {existing_file.file.name}"
            )


def file_upload_path(instance, filename):
    """Generate upload path: media/<resource name>/<version>.<ext>"""
    if instance.resource and instance.version:
        ext = os.path.splitext(filename)[1]
        return f"{instance.resource.name}/{instance.version}{ext}"
    return filename


class ResourceFile(models.Model):
    file = models.FileField(
        upload_to=file_upload_path,
        validators=[validate_media_file, validate_unique_checksum],
    )
    resource = models.ForeignKey(
        Resource, on_delete=models.CASCADE, related_name="resource_files"
    )
    audio_language = models.ForeignKey(
        "Language",
        on_delete=models.SET_NULL,
        default=None,
        null=True,
        blank=True,
        related_name="files_with_audio_language",
    )
    burned_in_subtitles_language = models.ForeignKey(
        "Language",
        on_delete=models.SET_NULL,
        default=None,
        null=True,
        blank=True,
        related_name="files_with_burned_in_subtitles",
    )
    version = models.CharField(max_length=100, blank=True)
    full_video = models.BooleanField(
        default=True,
        help_text="Does this file contain the entire work (i.e., not just a clip?)",
    )
    notes = models.TextField(blank=True)
    checksum = models.CharField(
        max_length=16, blank=True, editable=False, unique=True, null=True
    )
    checksum_at = models.DateTimeField(null=True, blank=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    barcode = models.CharField(
        null=True,
        blank=True,
        help_text="The EAN or UPC barcode on the resource. If there isn't one, an internal 'BYU' prefixed code will be assigned.",
    )

    def clean(self):
        super().clean()
        self.validate_barcode()

    def validate_barcode(self):
        if self.barcode is None:
            return
        barcode_len = len(self.barcode)
        if barcode_len < 12 or barcode_len > 13:
            raise ValidationError("Barcode must be 12 or 13 characters long.")

    def generate_barcode(self):
        """
        If we need to generate a barcode, that means the media doesn't have
        a UPC or EAN associated with it and we need to generate our own
        internally unique code.
        """
        self.barcode = "BYU" + str(self.id).zfill(10)
        self.save()

    def delete(self, *args, **kwargs):
        """Delete the file from the filesystem when the model is deleted."""
        if self.file:
            self.file.delete(save=False)
        super().delete(*args, **kwargs)

    def save(self, *args, **kwargs):
        """Generate checksum before saving."""
        if self.file and not self.checksum:
            self.checksum = _calculate_checksum_for_file(self.file)
            self.checksum_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.file} | {self.resource.name}"

    class Meta:
        unique_together = ("resource", "version")


class AnnotationSet(models.Model):
    """
    A set of annotations for a Resource.
    Multiple contents can use the same AnnotationSet.
    """

    name = models.CharField(max_length=255)
    resource = models.ForeignKey(
        "Resource", on_delete=models.CASCADE, related_name="annotation_sets"
    )
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="owned_annotation_sets"
    )
    editors = models.ManyToManyField(
        User, related_name="editable_annotation_sets", blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = [["name", "resource"]]
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} ({self.owner.first_name} {self.owner.last_name}) | {self.resource.name}"

    def can_edit(self, user):
        """Check if user can edit this annotation set."""
        return user == self.owner or user in self.editors.all() or user.is_admin

    def can_be_viewed_by(self, user):
        """Check if user can view this annotation set (through any content using the resource)."""
        return Content.objects.filter(
            resource=self.resource, playlist__owner=user
        ).exists() or self.can_edit(user)

    @classmethod
    def create_for_content(
        cls,
        content,
        user,
        set_name=None,
        annotation_set_json=None,
        annotation_set_id_to_copy=None,
    ):
        """
        Create a new AnnotationSet for a content's resource.
        Automatically adds playlist owner and instructor/TAs as editors.
        """

        try:
            playlist = content.playlist
            resource = content.get_resource()

            if not resource:
                raise ValueError(
                    "Content must be associated with a resource to create an AnnotationSet"
                )

            # Create annotation set with user as owner
            if set_name is not None and set_name != "":
                name = set_name
            else:
                name = f"{user.get_full_name()}'s Annotations"

            # check for set with the same name and resource combination
            existing_count = cls.objects.filter(
                name__startswith=name, resource=resource
            ).count()
            if existing_count > 0:
                name = f"{name} ({existing_count + 1})"

            annotation_set = cls.objects.create(
                name=name, resource=resource, owner=user
            )

            # Add all playlist instructors/TAs as editors
            instructors_and_tas = playlist.get_instructors_and_tas()
            annotation_set.editors.add(*instructors_and_tas)

            # create new annotations if provided (if importing from json, for example)
            if annotation_set_json is not None and isinstance(annotation_set_json, str):
                annotation_types = {
                    "SkipAnnotation": SkipAnnotation,
                    "MuteAnnotation": MuteAnnotation,
                    "BlankAnnotation": BlankAnnotation,
                    "PauseAnnotation": PauseAnnotation,
                    "BlurAnnotation": BlurAnnotation,
                    "CommentAnnotation": CommentAnnotation,
                }

                annotation_set_data = json.loads(annotation_set_json)
                for track in annotation_set_data.get("tracks", []):
                    Track.from_import(track, annotation_set)

                for annotation in annotation_set_data.get("annotations", []):
                    track = annotation_set.tracks.get(name=annotation.get("track_name"))
                    try:
                        annotation_class = annotation_types[annotation["class_type"]]
                        annotation_class.from_import(annotation, track)
                    except Exception as e:
                        logger.error(
                            f"Failed to import annotation. Annotation type: {annotation_class}. Exception: {e}"
                        )
                        continue

            # copying from pre-existing annotation set
            if annotation_set_json is None and annotation_set_id_to_copy is not None:
                annotation_set_to_copy = AnnotationSet.objects.get(
                    pk=annotation_set_id_to_copy
                )
                if set_name is None or set_name == "":
                    annotation_set.name = (
                        annotation_set_to_copy.name + f" (copied by {user.__str__})"
                    )
                annotations = (
                    annotation_set_to_copy.get_active_annotations_from_tracks()
                )
                for annotation in annotations:
                    annotation.copy_to_new_annotation_set(annotation_set)

            return annotation_set
        except Exception as e:
            logger.error(f"Failed to create annotation set. Exception: {e}")
            return None

    def get_tracks(self):
        """
        Get all tracks as they are
        """
        return sorted(self.tracks.all(), key=lambda track: track.stack_position)

    def get_highest_stack_position(self):
        track_with_highest_position_value = (
            self.tracks.all().order_by("stack_position").last()
        )
        return track_with_highest_position_value.stack_position

    def get_active_annotations_from_tracks(self):
        """
        Get all currently active annotations across all tracks.
        """
        annotations = []
        for track in list(self.tracks.all()):
            annotations.extend(track.get_active_annotations())
        return sorted(annotations, key=lambda a: a.start_time)

    def to_player_json(self):
        """Export all active annotations in this set for the AnnotationPlayer."""
        return {
            "tracks": [track.to_player_json() for track in self.get_tracks()],
            "annotations": [
                annotation.to_player_json()
                for annotation in self.get_active_annotations_from_tracks()
            ],
        }


class Track(models.Model):
    annotation_set = models.ForeignKey(
        AnnotationSet,
        on_delete=models.CASCADE,
        related_name="tracks",
        null=False,
        blank=False,
    )
    name = models.CharField(max_length=50, default="Track 1")
    stack_position = models.IntegerField(default=0)

    def get_active_annotations(self):
        """
        Get all currently active annotations across all types.
        Active annotations are the current state (tip of linked list).
        """
        annotations = []
        for model_class in [
            SkipAnnotation,
            MuteAnnotation,
            BlankAnnotation,
            PauseAnnotation,
            BlurAnnotation,
            CommentAnnotation,
            Clip,
        ]:
            annotations.extend(model_class.objects.filter(track=self, active=True))
        return sorted(annotations, key=lambda a: a.start_time)

    def is_final_stack_position(self):
        return self.annotation_set.get_highest_stack_position() == self.stack_position

    def to_player_json(self):
        """Export all active annotations in this set for the AnnotationPlayer."""
        return {"id": self.pk, "name": self.name, "stack_position": self.stack_position}

    def copy_to_new_annotation_set(self, annotation_set):
        # check if a track with this name exists in the new annotation set
        track_query_set = Track.objects.filter(
            annotation_set=annotation_set, name=self.name
        )
        if track_query_set.count() > 0:
            return track_query_set.first()
        else:
            new_track = Track.objects.create(
                annotation_set=annotation_set,
                name=self.name,
                stack_position=self.stack_position,
            )
            return new_track

    @classmethod
    def from_import(cls, imported_data, annotation_set):
        return cls.objects.create(
            annotation_set=annotation_set,
            name=imported_data.get("name", ""),
            stack_position=imported_data.get("stack_position", 0),
        )


class Content(models.Model):
    title = models.CharField(max_length=255)
    playlist = models.ForeignKey(
        Playlist,
        on_delete=models.CASCADE,
        related_name="contents",
        null=True,
        blank=True,
    )
    resource_file = models.ForeignKey(
        ResourceFile,
        on_delete=models.CASCADE,
        related_name="contents",
        null=True,
        blank=True,
    )
    resource = models.ForeignKey(
        Resource,
        on_delete=models.CASCADE,
        related_name="contents",
        null=True,
        blank=True,
    )
    annotation_set = models.ForeignKey(
        AnnotationSet,
        on_delete=models.SET_NULL,
        related_name="contents",
        null=True,
        blank=True,
    )
    url = models.URLField(max_length=500, blank=True, null=True)
    description = models.TextField(blank=True)
    allow_definitions = models.BooleanField(default=True)
    allow_notes = models.BooleanField(default=True)
    allow_captions = models.BooleanField(default=True)
    views = models.IntegerField(default=0, editable=False)
    published = models.BooleanField(default=False)
    words = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("playlist", "title")

    def __str__(self):
        playlist_name = self.playlist.name if self.playlist else "No Playlist"
        return f"{self.title} | {playlist_name} | {self.id}"

    def save(self, *args, **kwargs):
        if self.resource_file:
            self.resource = self.resource_file.resource
        super().save(*args, **kwargs)

    def get_resource(self):
        if self.resource_id:
            return self.resource
        if self.resource_file_id:
            return self.resource_file.resource
        return None

    def is_url_only(self):
        return self.resource_file_id is None and bool(self.url)

    def get_available_annotation_sets(self):
        """Get all AnnotationSets available for this content's resource."""
        resource = self.get_resource()
        if not resource:
            return AnnotationSet.objects.none()
        return AnnotationSet.objects.filter(resource=resource)

    def get_subtitles(self):
        """
        Get all subtitles as list of dicts for the AnnotationPlayer.
        Each dict has the following keys:
            - 'srclang'
            - 'vtt' or 'url'
            - 'label'
        """
        resource = self.get_resource()
        if not resource:
            return []
        sub_objs = Subtitle.objects.filter(resource=resource)
        subtitles = [
            {
                "id": sub.pk,
                "srclang": sub.language.lang_tag,
                "vtt": sub.subtitles_file.read().decode("utf-8"),
                "name": sub.name,
            }
            for sub in sub_objs
        ]
        return subtitles

    def get_player_json(self):
        """
        Generate complete JSON data for AnnotationPlayer.loadData().
        Returns a dict with 'annotations', each containing JSON strings.
        """
        annotation_set_json = (
            self.annotation_set.to_player_json()
            if self.annotation_set
            else {"annotations": [], "tracks": []}
        )
        return {
            "annotations": annotation_set_json["annotations"],
            "tracks": annotation_set_json["tracks"],
            "subtitleTracks": self.get_subtitles(),
        }


class ImportantWord(models.Model):
    content = models.ForeignKey(
        Content, on_delete=models.CASCADE, null=False, blank=False
    )
    word = models.CharField(null=False, blank=True, max_length=50)
    translation = models.CharField(null=False, blank=True, max_length=100)


class BaseAnnotation(models.Model):
    """
    Base class for all annotation types.
    Implements linked list for undo/redo functionality.
    Undo/redo is per-annotation: each annotation has its own version history.
    """

    name = models.CharField(max_length=255, blank=True)
    track = models.ForeignKey(
        Track,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_annotations",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    start_time = models.FloatField(default=0.0)
    end_time = models.FloatField(default=0.0)

    # Linked list pointers for undo/redo
    prev = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        related_name="%(app_label)s_%(class)s_prev_relation",
        null=True,
        blank=True,
    )
    next = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        related_name="%(app_label)s_%(class)s_next_relation",
        null=True,
        blank=True,
    )
    description = models.TextField(
        blank=False,
        null=False,
        help_text="Short description of what content this annotation covers.",
    )

    # Only active annotations are visible/used
    active = models.BooleanField(default=True)

    class Meta:
        abstract = True

    @property
    def annotation_type(self):
        """Return the annotation type string (e.g., 'skip', 'pause')."""
        return self.__class__.__name__.replace("Annotation", "").lower()

    def calculate_position(self):
        """Calculate visual position on timeline."""
        return {
            "left": "0%",
            "width": "0%",
            "start": self.start_time,
            "end": self.end_time,
        }

    def to_player_json(self):
        """Convert annotation to JSON format for video player."""
        start = float(self.start_time)
        end = float(self.end_time)
        return {
            "id": self.pk,
            "name": self.name,
            "type": self.annotation_type,
            "class_type": self.__class__.__name__,
            "start": start,
            "end": end,
            "start_display": seconds2hms(start),
            "end_display": seconds2hms(end),
            "label": self.name,
            "track_name": self.track.name,
            "description": self.description,
            "active": self.active,
        }

    def copy_to_new_annotation_set(self, annotation_set):
        new_track = self.track.copy_to_new_annotation_set(annotation_set)
        annotation_types = {
            "SkipAnnotation": SkipAnnotation,
            "MuteAnnotation": MuteAnnotation,
            "BlankAnnotation": BlankAnnotation,
            "PauseAnnotation": PauseAnnotation,
            "BlurAnnotation": BlurAnnotation,
            "CommentAnnotation": CommentAnnotation,
            "Clip": Clip,
        }
        new_annotation = annotation_types[self.__class__.__name__].objects.create(
            name=self.name,
            track=new_track,
            start_time=self.start_time,
            end_time=self.end_time,
            description=self.description,
            active=self.active,
        )
        return new_annotation

    @classmethod
    def from_import(cls, imported_data, track):
        return cls.objects.create(
            name=imported_data.get("name", ""),
            track=track,
            start_time=imported_data.get("start", 0.0),
            end_time=imported_data.get("end", 0.0),
            description=imported_data.get("description", ""),
            active=True,
        )

    @transaction.atomic
    def edit(self, **update_fields):
        """
        Edit this annotation by creating a new version in the linked list.
        """
        # Step 1: Mark this annotation as inactive
        self.active = False
        self.save()

        # Step 2: Recursively delete any next versions (clear redo history)
        self._delete_next_chain()

        # Step 3: Create new version with updated fields
        new_data = {
            field.name: getattr(self, field.name)
            for field in self._meta.fields
            if field.name
            not in ["id", "created_at", "updated_at", "prev", "next", "active"]
        }

        # Apply updates
        new_data.update(update_fields)

        # Create new annotation
        new_annotation = self.__class__.objects.create(
            **new_data, prev=self, next=None, active=True
        )

        # Step 4: Link new annotation as this annotation's next
        self.next = new_annotation
        self.save()

        return new_annotation

    def _delete_next_chain(self):
        """Recursively delete all next annotations in the chain."""
        if self.next is not None:
            next_annotation = self.next
            self.next = None
            self.save()

            # Recursively delete the rest of the chain
            next_annotation._delete_next_chain()
            next_annotation.delete()

    @transaction.atomic
    def delete_with_history(self):
        """
        Mark this annotation as deleted by creating an inactive version.
        """
        # Mark current as inactive
        self.active = False
        self.save()

        # Clear any redo history
        self._delete_next_chain()

    @transaction.atomic
    def undo(self):
        """
        Undo this annotation: revert to the previous version in the linked list.
        Returns the previous version if undo is possible, else None.
        """
        if self.prev is None:
            return None
        self.active = False
        self.save()
        self.prev.active = True
        self.prev.save()
        return self.prev

    @transaction.atomic
    def redo(self):
        """
        Redo this annotation: move forward to the next version in the linked list.
        Returns the next version if redo is possible, else None.
        """
        if self.next is None:
            return None
        self.active = False
        self.save()
        self.next.active = True
        self.next.save()
        return self.next

    def save(self, *args, **kwargs):
        self.start_time = round(float(self.start_time or 0), 2)
        self.end_time = round(float(self.end_time or 0), 2)
        super().save(*args, **kwargs)


class SkipAnnotation(BaseAnnotation):
    """Skip annotation - standard time range. Allows optional message to be displayed at the beginning of a skip."""

    message = models.TextField(max_length=255, blank=True)

    def calculate_position(self):
        return {
            "left": "0%",
            "width": "2px",
            "start": self.start_time,
            "end": self.end_time,
        }

    def to_player_json(self):
        data = super().to_player_json()  # includes start/end + display strings
        data["type"] = "skip"  # keep/ensure type
        data["message"] = self.message
        return data

    def copy_to_new_annotation_set(self, annotation_set):
        new_annotation = super().copy_to_new_annotation_set(annotation_set)
        new_annotation.message = self.message
        new_annotation.save()
        return new_annotation

    @classmethod
    def from_import(cls, imported_data, track):
        obj = super().from_import(imported_data, track)
        obj.message = imported_data.get("message", "")
        obj.save()
        return obj


class MuteAnnotation(BaseAnnotation):
    """Mute annotation - standard time range."""

    @classmethod
    def from_import(cls, imported_data, track):
        return super().from_import(imported_data, track)


class BlankAnnotation(BaseAnnotation):
    """Blank annotation - standard time range."""

    type = models.CharField(
        max_length=10,
        choices=[
            ("k", "Black"),  # <video> CSS filter: brightness(0)
            ("#", "Blur"),  # <video> CSS filter: blur(30px)
            ("w", "White"),  # <video> CSS filter: brightness(10)
        ],
        default="k",
    )

    def copy_to_new_annotation_set(self, annotation_set):
        new_annotation = super().copy_to_new_annotation_set(annotation_set)
        new_annotation.type = self.type
        new_annotation.save()
        return new_annotation

    @classmethod
    def from_import(cls, imported_data, track):
        obj = super().from_import(imported_data, track)
        obj.type = imported_data.get("type", "k")
        obj.save()
        return obj


class PauseAnnotation(BaseAnnotation):
    """Pause annotation - point in time, not a range."""

    message = models.TextField(max_length=255, blank=True, default="")

    def calculate_position(self):
        """Override: pause is a point marker, not a range."""
        return {
            "left": "0%",
            "width": "2px",
            "start": self.start_time,
            "end": self.start_time,  # TODO: Would None be better?
        }

    def to_player_json(self):
        """pause needs a start time even though it doesnt have an end time. This is because
        of how the AnnotationPlayer parses annotations for Y-video"""
        # TODO need to handle null end_time?
        data = super().to_player_json()
        data["message"] = self.message
        return data

    def copy_to_new_annotation_set(self, annotation_set):
        new_annotation = super().copy_to_new_annotation_set(annotation_set)
        new_annotation.message = self.message
        new_annotation.save()
        return new_annotation

    @classmethod
    def from_import(cls, imported_data, track):
        obj = super().from_import(imported_data, track)
        obj.message = imported_data.get("message", "")
        obj.save()
        return obj


def validate_font_color(hexcode):
    # font color must be at least 3 characters or 6 characters.
    font_color_length = len(hexcode)
    if font_color_length != 3 and font_color_length != 6:
        raise ValidationError(
            f"font_color must be 3 or 6 characters. {hexcode} was provided which has {font_color_length} characters."
        )
    # check that each character is [0-9], [a-f], or [A-F]
    pattern = "[0-9a-fA-F]"
    for char in hexcode:
        if re.search(pattern, char) is None:
            raise ValidationError(
                "font_color must only include valid hexadecimal characters: 0-9, a-f or A-F"
            )


class CommentAnnotation(BaseAnnotation):
    """Comment annotation with text and position."""

    text = models.TextField(default="This is where your comment will show")
    top_left_x = models.FloatField(default=0.0)
    top_left_y = models.FloatField(default=0.0)
    bottom_right_x = models.FloatField(default=100.0)
    bottom_right_y = models.FloatField(default=10.0)
    font_size_in_rem = models.FloatField(default=1)
    font_color = models.CharField(
        max_length=6, default="ffffff", validators=[validate_font_color]
    )

    @property
    def height(self):
        return (self.bottom_right_y - self.top_left_y) + "%"

    @property
    def width(self):
        return (self.bottom_right_x - self.top_left_x) + "%"

    def to_player_json(self):
        """Override: include text and coordinates."""
        data = super().to_player_json()
        data.update(
            {
                "text": self.text,
                "top_left_x": self.top_left_x,
                "top_left_y": self.top_left_y,
                "bottom_right_x": self.bottom_right_x,
                "bottom_right_y": self.bottom_right_y,
                "font_size_in_rem": self.font_size_in_rem,
                "font_color": self.font_color,
            }
        )
        return data

    def copy_to_new_annotation_set(self, annotation_set):
        new_annotation = super().copy_to_new_annotation_set(annotation_set)
        new_annotation.text = self.text
        new_annotation.top_left_x = self.top_left_x
        new_annotation.top_left_y = self.top_left_y
        new_annotation.bottom_right_x = self.bottom_right_x
        new_annotation.bottom_right_y = self.bottom_right_y
        new_annotation.font_size_in_rem = self.font_size_in_rem
        new_annotation.font_color = self.font_color
        new_annotation.save()
        return new_annotation

    @classmethod
    def from_import(cls, imported_data, track):
        new_annotation = super().from_import(imported_data, track)
        new_annotation.text = imported_data.get("text", "Your comment here")
        new_annotation.top_left_x = imported_data.get("top_left_x", 50.0)
        new_annotation.top_left_y = imported_data.get("top_left_y", 50.0)
        new_annotation.bottom_right_x = imported_data.get("bottom_right_x", 60.0)
        new_annotation.bottom_right_y = imported_data.get("bottom_right_y", 60.0)
        new_annotation.font_size_in_rem = imported_data.get("font_size_in_rem", 1.0)
        new_annotation.font_color = imported_data.get("font_color", "abcdef")
        new_annotation.save()
        return new_annotation


class BlurAnnotation(BaseAnnotation):
    def to_player_json(self):
        """Override: include positions data."""
        data = super().to_player_json()
        positions_query_set = self.positions.all().order_by("time")
        positions = []
        for position in positions_query_set:
            positions.append(
                {
                    "id": position.pk,
                    "time": position.time,
                    "x": position.x,
                    "y": position.y,
                    "width": position.width,
                    "height": position.height,
                    "blur_amount": position.blur_amount,
                    "type": position.type,
                }
            )
        data.update({"positions": positions, "type": "blur"})
        return data

    def get_position_locators(self):
        positions = self.positions.all().order_by("time")
        locators = []
        normalized_duration = self.end_time - self.start_time
        if normalized_duration <= 0:
            return locators
        for position in positions[1:]:
            relative_time = position.time - self.start_time
            locators.append(
                {
                    "id": position.pk,
                    "time": position.time,
                    "relative_location": round(
                        (relative_time / normalized_duration) * 100, 2
                    ),
                }
            )
        return locators

    def remove_positions_outside_of_timebox(self):
        positions = list(self.positions.all())
        position_index = len(positions) - 1
        while position_index >= 0:
            position = positions[position_index]
            if position.time != 0 and (
                position.time < self.start_time or position.time > self.end_time
            ):
                position.delete()
            position_index = position_index - 1

    def copy_to_new_annotation_set(self, annotation_set):
        new_annotation = super().copy_to_new_annotation_set(annotation_set)
        positions = self.positions.all()
        for position in positions:
            BlurAnnotationPosition.objects.create(
                blur_annotation=new_annotation,
                time=position.time,
                x=position.x,
                y=position.y,
                width=position.width,
                height=position.height,
                blur_amount=position.blur_amount,
                type=position.type,
            )
        new_annotation.save()
        return new_annotation

    @classmethod
    def from_import(cls, imported_data, track):
        obj = super().from_import(imported_data, track)
        for position in imported_data.get("positions", []):
            BlurAnnotationPosition.objects.create(
                blur_annotation=obj,
                time=position.get("time"),
                x=position.get("x"),
                y=position.get("y"),
                width=position.get("width"),
                height=position.get("height"),
                blur_amount=position.get("blur_amount", 60),
                type=position.get("type", "blur"),
            )
        return obj


class BlurAnnotationPosition(models.Model):
    blur_annotation = models.ForeignKey(
        BlurAnnotation,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        related_name="positions",
    )
    time = models.FloatField(null=False, blank=False)
    x = models.FloatField(null=False, blank=False)
    y = models.FloatField(null=False, blank=False)
    width = models.FloatField(null=False, blank=False)
    height = models.FloatField(null=False, blank=False)
    blur_amount = models.IntegerField(null=False, blank=False, default=60)
    type = models.TextField(null=False, blank=False, default="blur")  # TODO remove?

    @classmethod
    def validate(cls, data_dict):
        try:
            if data_dict["time"] < cls.blur_annotation.start_time:
                return (False, "Position cannot be before the annotation starts.")
            if data_dict["time"] > cls.blur_annotation.end_time:
                return (False, "Position cannot be after the annotation ends.")
            if (
                data_dict["x"] < 0
                or data_dict["y"] < 0
                or data_dict["width"] < 0
                or data_dict["height"] < 0
            ):
                return (False, "Position x, y, width, and height cannot be less than 0")
            return True, None
        except Exception as e:
            return False, f"Invalid position: {e}"


class Clip(BaseAnnotation):
    description = models.TextField(blank=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._meta.get_field(
            "description"
        ).help_text = "Short description of the scene this clip is showing"

    def __str__(self):
        return f"Clip {self.name} | {self.start_time}-{self.end_time} | {self.id}"


class Course(models.Model):
    dept = models.CharField(
        max_length=5,
        validators=[
            RegexValidator(
                regex=r"^[A-Z ]{2,5}$",
                message="Department must be 2 to 5 uppercase letters or spaces.",
                code="invalid_dept",
            )
        ],
    )
    catalog_number = models.CharField(
        max_length=4,
        validators=[
            RegexValidator(
                regex=r"^\d{3}R?$",
                message="Catalog number must be a 3-digit number (and optional 'R' suffix).",
                code="invalid_catalog_number",
            )
        ],
    )

    section_number = models.CharField(
        max_length=3,
        validators=[
            RegexValidator(
                regex=r"^\d{3}$",
                message="Section number must be 1 to 3 digits.",
                code="invalid_section_number",
            )
        ],
    )

    yearterm = models.CharField(max_length=5, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("dept", "catalog_number", "section_number", "yearterm")
        ordering = ["dept", "catalog_number", "section_number", "yearterm"]

    def display_yearterm(self):
        if not self.yearterm:
            return ""
        year_str = self.yearterm[:4]
        term_str = self.yearterm[4:]
        term_map = {"1": "Winter", "3": "Spring", "4": "Summer", "5": "Fall"}
        try:
            term_name = term_map[term_str]
        except KeyError:
            logger.error(
                f"Course has a missing or invalid yearterm. Course id: {self.pk}, yearterm: {self.yearterm}"
            )
            return self.yearterm
        return f"{term_name} {year_str}"

    def __str__(self):
        return f"{self.dept} {self.catalog_number}-{self.section_number} ({self.display_yearterm()})"


class UserCourses(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    yearterm = models.CharField(max_length=5, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def display_yearterm(self):
        if not self.yearterm:
            return ""
        year_str = self.yearterm[:4]
        term_str = self.yearterm[4:]
        term_map = {"1": "Winter", "3": "Spring", "4": "Summer", "5": "Fall"}
        try:
            term_name = term_map[term_str]
        except KeyError:
            logger.error(
                f"UserCourses has a missing or invalid yearterm. UserCourses id: {self.pk}, yearterm: {self.yearterm}"
            )
            return self.yearterm
        return f"{term_name} {year_str}"

    def __str__(self):
        return f"{self.course.dept} {self.course.catalog_number} Section {self.course.section_number} {self.display_yearterm()}"


class Language(models.Model):
    language = models.CharField(max_length=60, unique=True, blank=False, null=False)
    # TODO ensure that these are ISO 639-1 (2002) or a three-letter code from ISO 639-2 (1998), ISO 639-3 (2007) or ISO 639-5 (2008)
    lang_tag = models.CharField(max_length=10, unique=True, blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["language"]

    def __str__(self):
        return f"{self.language} ({self.lang_tag})"


def subtitle_file_upload_path(instance, filename):
    """Generate upload path to media/<resource name>/subtitles/<filename>"""
    if isinstance(instance, Subtitle):
        return f"{instance.resource.name}/subtitles/{filename}"


def subtitle_temp_file_upload_path(instance):
    """Generate upload path to media/<resource name>/subtitles/<filename>"""
    if isinstance(instance, Subtitle):
        return f"{instance.resource.name}/subtitles/{instance.name}_temp.vtt"


def validate_subtitle_file(file):
    """Ensure filetype is .vtt or .srt"""
    file_name_split = os.path.splitext(file.name)
    file_ext = file_name_split[1]
    if file_ext != ".vtt" and file_ext != ".srt":
        raise ValidationError(
            f"Subtitles must be .vtt or .srt format. Format provided: {file_ext}"
        )


class Subtitle(models.Model):
    resource = models.ForeignKey(
        Resource, on_delete=models.CASCADE, related_name="subtitles"
    )
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="subtitles"
    )
    language = models.ForeignKey(
        Language, on_delete=models.CASCADE, related_name="subtitles"
    )
    name = models.CharField(max_length=255)
    subtitles_file = models.FileField(
        upload_to=subtitle_file_upload_path,
        validators=[validate_subtitle_file],
    )
    subtitles_temp_file = models.FileField(
        upload_to=subtitle_temp_file_upload_path,
        validators=[validate_subtitle_file],
        null=True,
        blank=True,
    )
    is_original = models.BooleanField(null=False, blank=False, default=False)
    words = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} | {self.language.language} | {self.resource.name} | {self.owner.first_name} {self.owner.last_name} | {self.id}"

    class Meta:
        unique_together = ("resource", "owner", "language", "name")


class ResourceFileKey(models.Model):  # "through" model
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="resource_file_keys",
    )
    resource_file = models.ForeignKey(
        ResourceFile, on_delete=models.CASCADE, related_name="resource_file_keys"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name} | {self.resource_file.resource.name} | {self.resource_file.version} | {self.id}"


class Email(models.Model):
    sender = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="emails"
    )
    sender_email = models.EmailField(max_length=255)
    recipients = models.JSONField()
    subject = models.CharField(max_length=255)
    body = models.TextField()
    sent_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.sender.netid} | {self.subject} | {self.pk}"


class AuthToken(models.Model):
    token = models.CharField(max_length=150, null=True)
    created_at = models.DateTimeField(auto_now_add=True)


def get_date_5_days_from_now():
    return timezone.localdate() + timedelta(days=5)


class ResourceIntakeRequest(models.Model):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    date_needed = models.DateField(default=get_date_5_days_from_now)
    generated_resource = models.ForeignKey(
        Resource,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="intake_requests",
    )

    # Resource-specific fields
    resource_title = models.CharField(default="")
    imdb_link = models.URLField(default="", blank=True)
    audio_language = models.CharField(default="", blank=True)
    subtitle_language = models.CharField(default="", blank=True)

    # Checkout information
    checked_out_from_hbll = models.BooleanField(default=False)
    checked_out_from_other_byu_library = models.BooleanField(default=False)

    # Content advisory fields
    violence_or_blood_and_gore = models.BooleanField(default=False)
    nudity_or_sexual_content = models.BooleanField(default=False)
    profanity_or_vulgarity = models.BooleanField(default=False)
    self_harm_or_suicide = models.BooleanField(default=False)
    drug_use = models.BooleanField(default=False)

    # Legal compliance
    acknowledged_compliance = models.BooleanField(default=False)
    acknowledged_fair_use_limitation = models.BooleanField(default=False)

    def __str__(self):
        return f"Content request for {self.resource_title} by {self.owner} due by {self.date_needed}"
