"""Django settings for yvideo project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

try:
    from . import secret_settings
except ImportError:
    import warnings

    warnings.warn(
        "secret_settings.py not found; falling back to secret_settings_template.py",
        stacklevel=1,
    )
    from . import secret_settings_template as secret_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _resolve_repo_path(raw_value):
    if raw_value in (None, ""):
        return None
    path_value = Path(raw_value)
    if path_value.is_absolute():
        return path_value
    return BASE_DIR / path_value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secret_settings.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = secret_settings.DEBUG
DEV_QUICK_LOGIN_ENABLED = getattr(secret_settings, "DEV_QUICK_LOGIN_ENABLED", False)
DEV_QUICK_LOGIN_HOSTS = getattr(secret_settings, "DEV_QUICK_LOGIN_HOSTS", tuple())

ALLOWED_HOSTS = secret_settings.ALLOWED_HOSTS

SECURE_PROXY_SSL_HEADER = getattr(secret_settings, "SECURE_PROXY_SSL_HEADER", None)
CSRF_TRUSTED_ORIGINS = getattr(secret_settings, "CSRF_TRUSTED_ORIGINS", [])

LOGIN_URL = "oidc_authentication_init"

# Application definition
AUTH_USER_MODEL = "core.User"

AUTHENTICATION_BACKENDS = [
    "yvideo.odhOIDCAuthenticationBackend.OIDCUserAuth",
    "django.contrib.auth.backends.ModelBackend",
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "mozilla_django_oidc",  # must load after auth
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.sessions",
    "django.contrib.staticfiles",
    "reversion",  # django-reversion
    "core.apps.CoreConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "core.middleware.SpoofUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "mozilla_django_oidc.middleware.SessionRefresh",
]

ROOT_URLCONF = "yvideo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core/templates/core"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.feature_flags",
            ],
        },
    },
]

WSGI_APPLICATION = "yvideo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

_DB_DIR = Path(os.environ.get("YVIDEO_DB_DIR", str(BASE_DIR)))

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": _DB_DIR / "db.sqlite3",
        "OPTIONS": {
            "init_command": "PRAGMA journal_mode=wal;PRAGMA synchronous=NORMAL; PRAGMA mmap_size=134217728; PRAGMA journal_size_limit=67108864; PRAGMA cache_size=2000;",
        },
    }
}

LEGACY_MIGRATION_ENABLED = getattr(secret_settings, "LEGACY_MIGRATION_ENABLED", False)
LEGACY_MIGRATION_MEDIA_ROOT = getattr(
    secret_settings, "LEGACY_MIGRATION_MEDIA_ROOT", ""
)
LEGACY_MIGRATION_DB_ALIAS = getattr(
    secret_settings, "LEGACY_MIGRATION_DB_ALIAS", "legacy"
)
LEGACY_MIGRATION_SQLITE_PATH = _resolve_repo_path(
    getattr(
        secret_settings,
        "LEGACY_MIGRATION_SQLITE_PATH",
        "var/legacy_migration/legacy_dump.sqlite3",
    )
)
LEGACY_MIGRATION_CREATE_MISSING_USERS = getattr(
    secret_settings, "LEGACY_MIGRATION_CREATE_MISSING_USERS", False
)
LEGACY_MIGRATION_DUMP_SCRIPT = str(
    _resolve_repo_path(
        getattr(
            secret_settings,
            "LEGACY_MIGRATION_DUMP_SCRIPT",
            "scripts/dump_legacy_to_sqlite.py",
        )
    )
)

if LEGACY_MIGRATION_SQLITE_PATH:
    DATABASES[LEGACY_MIGRATION_DB_ALIAS] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": LEGACY_MIGRATION_SQLITE_PATH,
    }

CONN_MAX_AGE = 600
CONN_HEALTH_CHECKS = True


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = secret_settings.TIME_ZONE

USE_I18N = True

USE_TZ = True

# OIDC Settings
OIDC_RP_CLIENT_ID = secret_settings.OIDC_RP_CLIENT_ID
OIDC_RP_CLIENT_SECRET = secret_settings.OIDC_RP_CLIENT_SECRET
OIDC_RP_SIGN_ALGO = secret_settings.OIDC_RP_SIGN_ALGO
OIDC_OP_AUTHORIZATION_ENDPOINT = secret_settings.OIDC_OP_AUTHORIZATION_ENDPOINT
OIDC_OP_TOKEN_ENDPOINT = secret_settings.OIDC_OP_TOKEN_ENDPOINT
OIDC_OP_USER_ENDPOINT = secret_settings.OIDC_OP_USER_ENDPOINT
OIDC_OP_JWKS_ENDPOINT = secret_settings.OIDC_OP_JWKS_ENDPOINT
LOGIN_REDIRECT_URL = secret_settings.LOGIN_REDIRECT_URL
LOGOUT_REDIRECT_URL = secret_settings.LOGOUT_REDIRECT_URL
OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS = (
    secret_settings.OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS
)  # 12 hours in seconds
OIDC_USE_PKCE = secret_settings.OIDC_USE_PKCE
OIDC_PKCE_CODE_CHALLENGE_METHOD = secret_settings.OIDC_PKCE_CODE_CHALLENGE_METHOD

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Logging
# https://docs.djangoproject.com/en/5.1/topics/logging/
#
# Send logs to stderr so Gunicorn's --error-logfile captures them and they land
# in journald/`podman logs`. Unlike Django's default config, the console handler
# here has no `require_debug_true` filter, so `django.request` errors (the 500
# tracebacks) are recorded even when DEBUG is False.

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{levelname}] {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "mozilla_django_oidc": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
